# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaMax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperaturaMin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('luminosidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distanciaLinea', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='faseCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('diasDuracion', models.IntegerField()),
                ('hidricos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('siembra', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='siembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='simulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lineaSiembra', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('confi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrar.configuracion')),
                ('fase', models.ManyToManyField(to='administrar.faseCultivo')),
                ('siembra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar.siembra')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=250)),
                ('estado', models.IntegerField()),
                ('tipoU', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrar.tipoUsuario')),
            ],
        ),
        migrations.AddField(
            model_name='simulacion',
            name='usu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar.usuario'),
        ),
    ]
