# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.tipoUsuario'),
        ),
    ]
