# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0002_auto_20180628_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasecultivo',
            name='siembra',
            field=models.CharField(max_length=50),
        ),
    ]
