# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0003_auto_20180707_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasecultivo',
            name='etapa',
            field=models.CharField(max_length=50),
        ),
    ]
